"""Tesla Fleet API constants."""
from enum import StrEnum


class Errors(StrEnum):
    """Tesla Fleet API error codes."""

    INVALID_COMMAND = "invalid_command"
    INVALID_FIELD = "invalid_field"
    INVALID_REQUEST = "invalid_request"
    INVALID_TOKEN = "invalid_token"  # Teslemetry specific
    INVALID_AUTH_CODE = "invalid_auth_code"
    INVALID_REDIRECT_URL = "invalid_redirect_url"
    UNAUTHORIZED_CLIENT = "unauthorized_client"
    MOBILE_ACCESS_DISABLED = "mobile_access_disabled"


SERVERS = {
    "na": "https://fleet-api.prd.na.vn.cloud.tesla.com",
    "eu": "https://fleet-api.prd.eu.vn.cloud.tesla.com",
    "cn": "https://fleet-api.prd.cn.vn.cloud.tesla.cn",
}


TELEMETRY_FIELDS = (
    "ACChargingEnergyIn",
    "ACChargingPower",
    "AutoSeatClimateLeft",
    "AutoSeatClimateRight",
    "AutomaticBlindSpotCamera",
    "AutomaticEmergencyBrakingOff",
    "BMSState",
    "BatteryHeaterOn",
    "BatteryLevel",
    "BlindSpotCollisionWarningChime",
    "BmsFullchargecomplete",
    "BrakePedal",
    "BrakePedalPos",
    "BrickVoltageMax",
    "BrickVoltageMin",
    "CarType",
    "ChargeAmps",
    "ChargeCurrentRequest",
    "ChargeCurrentRequestMax",
    "ChargeEnableRequest",
    "ChargeLimitSoc",
    "ChargePort",
    "ChargePortColdWeatherMode",
    "ChargePortLatch",
    "ChargeState",
    "ChargerPhases",
    "CruiseFollowDistance",
    "CruiseSetSpeed",
    "CruiseState",
    "CurrentLimitMph",
    "DCChargingEnergyIn",
    "DCChargingPower",
    "DCDCEnable",
    "DestinationLocation",
    "DiAxleSpeedF",
    "DiAxleSpeedR",
    "DiAxleSpeedREL",
    "DiAxleSpeedRER",
    "DiHeatsinkTF",
    "DiHeatsinkTR",
    "DiHeatsinkTREL",
    "DiHeatsinkTRER",
    "DiMotorCurrentF",
    "DiMotorCurrentR",
    "DiMotorCurrentREL",
    "DiMotorCurrentRER",
    "DiSlaveTorqueCmd",
    "DiStateF",
    "DiStateR",
    "DiStateREL",
    "DiStateRER",
    "DiStatorTempF",
    "DiStatorTempR",
    "DiStatorTempREL",
    "DiStatorTempRER",
    "DiTorqueActualF",
    "DiTorqueActualR",
    "DiTorqueActualREL",
    "DiTorqueActualRER",
    "DiTorquemotor",
    "DiVBatF",
    "DiVBatR",
    "DiVBatREL",
    "DiVBatRER",
    "DoorState",
    "DriveRail",
    "DriverSeatBelt",
    "DriverSeatOccupied",
    "EmergencyLaneDepartureAvoidance",
    "EnergyRemaining",
    "EstBatteryRange",
    "Experimental_1",
    "Experimental_2",
    "Experimental_3",
    "Experimental_4",
    "ExteriorColor",
    "FastChargerPresent",
    "FdWindow",
    "ForwardCollisionWarning",
    "FpWindow",
    "Gear",
    "GpsHeading",
    "GpsState",
    "GuestModeEnabled",
    "GuestModeMobileAccessState",
    "Hvil",
    "IdealBatteryRange",
    "InsideTemp",
    "IsolationResistance",
    "LaneDepartureAvoidance",
    "LateralAcceleration",
    "LifetimeEnergyGainedRegen",
    "LifetimeEnergyUsed",
    "LifetimeEnergyUsedDrive",
    "Location",
    "Locked",
    "LongitudinalAcceleration",
    "MilesToArrival",
    "MinutesToArrival",
    "ModuleTempMax",
    "ModuleTempMin",
    "NotEnoughPowerToHeat",
    "NumBrickVoltageMax",
    "NumBrickVoltageMin",
    "NumModuleTempMax",
    "NumModuleTempMin",
    "Odometer",
    "OriginLocation",
    "OutsideTemp",
    "PackCurrent",
    "PackVoltage",
    "PairedPhoneKeyAndKeyFobQty",
    "PassengerSeatBelt",
    "PedalPosition",
    "PinToDriveEnabled",
    "PreconditioningEnabled",
    "RatedRange",
    "RdWindow",
    "RoofColor",
    "RouteLastUpdated",
    "RouteLine",
    "RpWindow",
    "ScheduledChargingMode",
    "ScheduledChargingPending",
    "ScheduledChargingStartTime",
    "ScheduledDepartureTime",
    "SeatHeaterLeft",
    "SeatHeaterRearCenter",
    "SeatHeaterRearLeft",
    "SeatHeaterRearRight",
    "SeatHeaterRight",
    "SentryMode",
    "ServiceMode",
    "Soc",
    "SpeedLimitMode",
    "SpeedLimitWarning",
    "SuperchargerSessionTripPlanner",
    "TimeToFullCharge",
    "TpmsLastSeenPressureTimeFl",
    "TpmsLastSeenPressureTimeFr",
    "TpmsLastSeenPressureTimeRl",
    "TpmsLastSeenPressureTimeRr",
    "TpmsPressureFl",
    "TpmsPressureFr",
    "TpmsPressureRl",
    "TpmsPressureRr",
    "Trim",
    "VehicleName",
    "VehicleSpeed",
    "Version",
)
TELEMETRY_ALERTS = (
    "Customer",
    "Service",
    "ServiceFix",
)
